"""create audit logs table

Revision ID: 39d0cad20c36
Revises: 4af598f96850
Create Date: 2026-07-13 10:47:41.834582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39d0cad20c36"
down_revision: Union[str, Sequence[str], None] = "4af598f96850"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_logs",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.alter_column(
        "audit_logs",
        "error_message",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_audit_logs_request_id"),
        table_name="audit_logs",
        postgresql_ops={"request_id": None},
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False
    )
    # ix_users_email already exists from the initial users migration (991e2ce09de4).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.create_index(
        op.f("ix_audit_logs_request_id"),
        "audit_logs",
        [sa.literal_column("request_id NULLS FIRST")],
        unique=False,
        postgresql_ops={"request_id": None},
        postgresql_using="prefix",
    )
    op.alter_column(
        "audit_logs",
        "error_message",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("audit_logs", "updated_at")
    # ### end Alembic commands ###
